
# [RRN] node image has too old versions for certain packages we use:
# FROM node:25
FROM ubuntu:25.10

# [RRN] TZ confuses happy-coder
# ARG TZ
# ENV TZ="$TZ"

ARG CLAUDE_CODE_VERSION=latest

# Installs a TON of stufF:
RUN apt-get update && apt-get install -y npm

# Stolen from the nodejs/docker/node Dockerfile:
# RUN groupadd --gid 1000 node \
#   && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

# Install basic development tools and iptables/ipset
RUN apt-get install -y --no-install-recommends \
  less \
  git \
  procps \
  sudo \
  fzf \
  zsh \
  man-db \
  unzip \
  gnupg2 \
  gh \
  iptables \
  ipset \
  iproute2 \
  dnsutils \
  aggregate \
  jq \
  nano \
  vim \
  wget \
  curl
  # [RRN ] Don't clean because we want to keep apt and I don't mind if claude
  # installs either:
  # && apt-get clean && rm -rf /var/lib/apt/lists/*

# [RRN] Differ in the non-root user we use from the node image:
# ENV MYUSER=node
ENV MYUSER=ubuntu

# Ensure default node user has access to /usr/local/share
RUN mkdir -p /usr/local/share/npm-global && \
  chown -R $MYUSER:$MYUSER /usr/local/share

ARG USERNAME=$MYUSER

# [RRN] Seems unimportant. We mount home dir from host anyway.
# Persist bash history.
# RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
  # && mkdir /commandhistory \
  # && touch /commandhistory/.bash_history \
  # && chown -R $USERNAME /commandhistory

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true

# Create workspace and config directories and set permissions
RUN mkdir -p /workspace /home/$MYUSER/.claude && \
  chown -R $MYUSER:$MYUSER /workspace /home/$MYUSER/.claude

WORKDIR /workspace

ARG GIT_DELTA_VERSION=0.18.2
RUN ARCH=$(dpkg --print-architecture) && \
  wget "https://github.com/dandavison/delta/releases/download/${GIT_DELTA_VERSION}/git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb" && \
  sudo dpkg -i "git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb" && \
  rm "git-delta_${GIT_DELTA_VERSION}_${ARCH}.deb"

# Set up non-root user
USER $MYUSER

# Install global packages
ENV NPM_CONFIG_PREFIX=/usr/local/share/npm-global
ENV PATH=$PATH:/usr/local/share/npm-global/bin

# [RRN] Uh, I don't know why claude needs to be opinionated about shell..
# Set the default shell to zsh rather than sh
# ENV SHELL=/bin/zsh

# Set the default editor and visual
ENV EDITOR=nano
ENV VISUAL=nano

# Default powerline10k theme
# ARG ZSH_IN_DOCKER_VERSION=1.2.0
# RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
#   -p git \
#   -p fzf \
#   -a "source /usr/share/doc/fzf/examples/key-bindings.zsh" \
#   -a "source /usr/share/doc/fzf/examples/completion.zsh" \
#   -a "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
#   -x

# Install Claude
RUN npm install -g @anthropic-ai/claude-code@${CLAUDE_CODE_VERSION}


# Copy and set up firewall script
COPY init-firewall.sh /usr/local/bin/
USER root
RUN chmod +x /usr/local/bin/init-firewall.sh && \
  echo "node ALL=(root) NOPASSWD: /usr/local/bin/init-firewall.sh" > /etc/sudoers.d/node-firewall && \
  chmod 0440 /etc/sudoers.d/node-firewall
USER $MYUSER
# End claude-related dependencies and setup.

RUN npm install -g happy-coder

# [RRN] basic additiions I like everywhere.
RUN apt-get install -y time parallel hyperfine bc
# [RRN] Python is so universal for scripting...
RUN apt-get install -y python3 pip python3-venv
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/python3 -m pip install uv
# End shared, non-project configuration.

