
# [RRN] node image has too old versions for certain packages we use:
# FROM node:25
FROM ubuntu:25.10

# [RRN] TZ confuses happy-coder
# ARG TZ
# ENV TZ="$TZ"

# Stolen from the nodejs/docker/node Dockerfile:
# RUN groupadd --gid 1000 node \
#   && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

# Install basic development tools and iptables/ipset
RUN apt-get update && apt-get install -y --no-install-recommends \
  less \
  git \
  procps \
  sudo \
  fzf \
  zsh \
  man-db \
  unzip \
  gnupg2 \
  gh \
  iptables \
  ipset \
  iproute2 \
  dnsutils \
  aggregate \
  jq \
  nano \
  vim \
  wget \
  curl
  # [RRN ] Don't clean because we want to keep apt and I don't mind if claude
  # installs either:
  # && apt-get clean && rm -rf /var/lib/apt/lists/*

# Installs a TON of stufF:
# RUN apt-get install -y npm

# Going to a newer version for github copilot
RUN apt-get install -y ca-certificates && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

ARG NODE_VERSION=24

RUN . "$HOME/.nvm/nvm.sh" && nvm install ${NODE_VERSION} && \
    nvm alias default ${NODE_VERSION} && nvm use default && \
    which node && node -v && npm -v 

# Hack to discover the minor version: e.g. /bin/versions/node/v24.11.0/bin/node
RUN cd /bin/versions/node/ && ln -s v24* 24
ENV PATH=$PATH:/bin/versions/node/24/bin/

# Install global packages
# ENV NPM_CONFIG_PREFIX=/usr/local/share/npm-global
# ENV PATH=$PATH:/usr/local/share/npm-global/bin

# [RRN] Differ in the non-root user we use from the node image:
# ENV MYUSER=node
ENV MYUSER=ubuntu

# Ensure default node user has access to /usr/local/share
RUN mkdir -p /usr/local/share/npm-global && \
  chown -R $MYUSER:$MYUSER /usr/local/share

ARG USERNAME=$MYUSER

# [RRN] Seems unimportant. We mount home dir from host anyway.
# Persist bash history.
# RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
  # && mkdir /commandhistory \
  # && touch /commandhistory/.bash_history \
  # && chown -R $USERNAME /commandhistory

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true

# [RRN] Uh, I don't know why claude needs to be opinionated about shell..
# Set the default shell to zsh rather than sh
# ENV SHELL=/bin/zsh

# Set the default editor and visual
ENV EDITOR=nano
ENV VISUAL=nano

# Default powerline10k theme
# ARG ZSH_IN_DOCKER_VERSION=1.2.0
# RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
#   -p git \
#   -p fzf \
#   -a "source /usr/share/doc/fzf/examples/key-bindings.zsh" \
#   -a "source /usr/share/doc/fzf/examples/completion.zsh" \
#   -a "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
#   -x


# [RRN] basic additiions I like everywhere.
# psmisc has killall:
RUN apt-get install -y time parallel hyperfine bc emacs gnuplot psmisc ssh

# [RRN] Python is so universal for scripting...
RUN apt-get install -y python3 pip python3-venv
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/python3 -m pip install uv
# End shared, non-project configuration.

# [RRN] Run my version, but cannot do it in a one-liner because of build step:
RUN . "$HOME/.nvm/nvm.sh" && \
    npm install -g happy-coder
# Shelving my version for now which just added --set-title.
    # git clone --depth=1 https://github.com/rrnewton/happy-cli.git /tmp/happy && \
    #   cd /tmp/happy && npm install && npm run build && npm install -g . && \
    #   rm -rf /tmp/happy


# Create workspace and config directories and set permissions
#RUN mkdir -p /workspace /home/$MYUSER/.claude && \
#  chown -R $MYUSER:$MYUSER /workspace /home/$MYUSER/.claude

# WORKDIR /workspace

# USER $MYUSER
ENV SHELL=/bin/bash
