
# Keep it out of the home dir because we will mount that from host:
RUN apt-get install rustup
ENV CARGO_HOME=/opt/cargo
ENV RUSTUP_HOME=/opt/multirust
RUN mkdir -p "$CARGO_HOME" && rustup toolchain install nightly
# RUN mkdir -p "$CARGO_HOME" && rustup toolchain install stable

# Install my minibeads tool for issue tracking
RUN cargo install --git https://github.com/rrnewton/minibeads --tag v0.4

RUN apt-get install -y heaptrack
RUN cargo install cargo-heaptrack cargo-nextest

